packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  electron: true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  maplibre-gl: true
  msgpackr-extract: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.9.17'
  - '@turbo/darwin-arm64@2.9.17'
  - '@turbo/linux-64@2.9.17'
  - '@turbo/linux-arm64@2.9.17'
  - '@turbo/windows-64@2.9.17'
  - '@turbo/windows-arm64@2.9.17'
  - turbo@2.9.17
  - '@turbo/darwin-64@2.9.18'
  - '@turbo/darwin-arm64@2.9.18'
  - '@turbo/linux-64@2.9.18'
  - '@turbo/linux-arm64@2.9.18'
  - '@turbo/windows-64@2.9.18'
  - '@turbo/windows-arm64@2.9.18'
  - turbo@2.9.18
