import type { CheckerTool } from '../types/tool.js';


export const CHECKER_TOOLS_CATALOG: CheckerTool[] = [
  {
    id: "proxy-checker",
    name: "Proxy Checker",
    description: "Check the validity of a proxy",
    icon: "material-symbols:vpn-googleone",
    badgeColor: "green",
    category: "proxy",
    color: "green",
    status: "active",
    url: "/app/tools/proxy-checker",
  },
  {
    id: "proxy-scraper",
    name: "Proxy Scraper",
    description: "Scrape a proxy from a website",
    icon: "material-symbols:vpn-googleone",
    badgeColor: "green",
    category: "proxy",
    color: "green",
    status: "active",
    url: "/app/tools/proxy-scraper",
  },
  {
    id: "fingerprint-generator",
    name: "Fingerprint Generator",
    description: "Generate a fingerprint",
    icon: "ooui:user-anonymous",
    badgeColor: "violet",
    category: "fingerprint",
    color: "violet",
    status: "active",
    url: "/app/tools/fingerprint-generator",
  },
  {
    id: "fingerprint-validator",
    name: "Fingerprint Validator",
    description: "Check the validity of a fingerprint",
    icon: "ooui:user-anonymous",
    badgeColor: "violet",
    category: "fingerprint",
    color: "violet",
    status: "active",
    url: "/app/tools/fingerprint-validator",
  },
  {
    id: "auto-checkout",
    name: "Auto Checkout",
    description: "Automatically complete a checkout",
    icon: "ic:sharp-shopping-cart-checkout",
    badgeColor: "sky",
    category: "checkout",
    color: "sky",
    status: "active",
    url: "/app/tools/auto-checkout",
  },
  {
    id: "auto-create-account",
    name: "Auto Create Account",
    description: "Automatically create an account",
    icon: "material-symbols:account-circle",
    badgeColor: "sky",
    category: "account",
    color: "sky",
    status: "active",
    url: "/app/tools/auto-create-account",
  },
]
